name: mpc_drone
channels:
  - conda-forge
  - defaults
  - gurobi
dependencies:
  - python=3.8
  - ipykernel
  - cvxpy
  - scikit-learn
  - matplotlib
  - numpy
  - tqdm
  - black
  - gurobi
  - tqdm
  - scipy
  - control
  - slycot
